apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
      [entryPoints.websecure]
        address = ":443"

    [certificatesResolvers.le.acme]
      email = "your-email@example.com"
      storage = "/data/acme.json"
      [certificatesResolvers.le.acme.httpChallenge]
        entryPoint = "web"
